# Site settings
title: Proyecto de Altas Capacidades en Matemáticas
email: Virgilio.Gomez@uclm.es
description: "Web del proyecto de Altas Capacidades en Matemáticas, Albacete, España"
url: "acmalbacete.github.io"
timezone: Europe/Madrid
encoding: UTF-8
